### ISSUE TITLE
Question: does it support v1.2.0-dev4 or v1.2.0 version?

### ISSUE THREAD

**Issue by michael-kotliar** [rabix/cwl-ts#123]
Just curious if this package can properly parse CWL files with `cwlVersion: v1.2.0-dev4` or `cwlVersion: v1.2.0`

Thanks

**Comment by milosdanilov** [comment]
Not yet, we are working on the support for CWL v1.2

**Comment by michael-kotliar** [comment]
Will it just fail to parse the workflow if the version is set to 1.2 or assume that it's previous version?

Thanks

**Comment by milosdanilov** [comment]
@michael-kotliar I think that it should properly deserialize for the parts of the CWL that it has support of, so by that logic I think that it should be compatible with CWL v1.2, i.e it should automatically downgrade 1.2 to 1.1 version.

I don't think that it should fail, but I can't guarantee that it's going to be stable in all situations. Maybe you can try on some example?

**Comment by michael-kotliar** [comment]
Ok, thank you for the information, I will check it
