### ISSUE TITLE
Add steps on the fly

### ISSUE THREAD

**Issue by yoanncouillec** [rabix/cwl-ts#75]
https://github.com/rabix/cwl-ts/blob/c8355c53a51df7721b440a575a705e71dad522e1/src/models/generic/WorkflowModel.ts#L1077

Would it be possible to make this method public ?
Then it would be possible to create steps on the fly.

**Comment by renaudpawlak** [comment]
Also, there is a public method ``addStepFromProcess``, however, I have no clues on how to use it. Would it be possible to have some advice about adding steps to an existing workflow?
Ultimately, what we would like to have is a step description in json. Then we create a step model or a process from it, then we add it to a workflow model. Do you think it is doable with the current API? If not, any plan to make it happen?

**Comment by yoanncouillec** [comment]
Thx Renaud and Ivan.
I was able to add a step with
```
var run = {"cwlVersion":"sbg:draft-2", ...};
workflow.model.addStepFromProcess(run);
```
variable run contains what should be in "run" field of each step of the workflow
