### ISSUE TITLE
build package leads to typescript compiler error

### ISSUE THREAD

**Issue by yoanncouillec** [rabix/cwl-ts#78]
Hi all!

I try to compile my own version of CWL-TS.

I followed readme instructions by running `scripts/package.sh`.
However it raises many typescript compiler errors.

Has someone been able to build CWL-TS locally ?

Thanks!

Y.

**Comment by bogdang989** [comment]
I encountered the same issue. @yoanncouillec did you manage to get it compiled?

**Comment by ivanbatic** [comment]
Docs are outdated, you can run ‘npm run publish:prepare’ to compile.
